<h1>Контакты</h1>
<a href="/book/contact/add/">Добавить</a><br><br>
<?php
    $flash = $this->flashMessenger();
    $flash->setMessageOpenFormat('<div%s>
            <button id="btn-message-close" type="button class="close" data-dismiss="alert" aria-hidden="true">
                &times;
            </button>
            <ul><li>')
            ->setMessageSeparatorString('</li><li>')
            ->setMessageCloseString('</li></ul></div>');
    
    echo $flash->render('error', array('alert', 'alert-dismissable', 'alert-danger'));
    echo $flash->render('info', array('alert', 'alert-dismissable', 'alert-info'));
    echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
    echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
?>
<table class="table table-striped table-hover">
    <tbody>
        <tr>
            <th>#</th>
            <th>Имя</th>
            <th>Фамилия</th>
            <th>Отчество</th>
            <th>Действие</th>
        </tr>
    </tbody>
    <?php 
    foreach ($contact as $item){
        echo "<tr>
                <td>{$item->getId()}</td>
                <td>{$item->getName()}</td>
                <td>{$item->getLastName()}</td>
                <td>{$item->getFatherName()}</td>";
        echo   '<td><a href="'.$this->url('book/contact', array('action' => 'view', 'id' => $item->getId())).'">Просмотреть</a>&nbsp;&nbsp;
                    <a href="'.$this->url('book/contact', array('action' => 'edit', 'id' => $item->getId())).'">Редактировать</a>&nbsp;&nbsp;
                    <a href="'.$this->url('book/contact', array('action' => 'delete', 'id' => $item->getId())).'" onclick="if (confirm(\'Удалить запись?\')) {document.location = this.href; } return false;">Удалить</a></td>';
    }
    ?>
</table>
