<h1>Просмотр контакта</h1>
<br><a href="/book/contact/">Назад</a><br><br>
<table class="table table-striped table-hover">
    <tbody>
        <tr>
            <th>#</th>
            <th>Имя</th>
            <th>Фамилия</th>
            <th>Отчество</th>
        </tr>
    </tbody>
    <?php 
    foreach ($contact as $item){
        echo "<tr>
                <td>{$item->getId()}</td>
                <td>{$item->getName()}</td>
                <td>{$item->getLastName()}</td>
                <td>{$item->getFatherName()}</td>"
                . "</tr>";
    }
    ?>
</table>
<table class="table table-striped table-hover">
    <tbody>
        <tr>
            <th>Телефоны</th>
        </tr>
    </tbody>
    <?php 
    foreach ($phones as $item){
        echo "<tr><td>{$item->getPhone()}</td></tr>";
    }
    ?>
</table>
